Edit and view organisations and units
nhsengland/innovation-service-transactional-frontend pull request #149
Opened 2022-04-06 14:26 UTC by AjayG0910

2022-04-06 15:12 UTC, JyotiJaiswal169 approved these changes

2022-04-06 16:22 UTC, BJSS-RicardoTavares requested changes

2022-04-06 16:22 UTC, BJSS-RicardoTavares commented on src/modules/feature-modules/admin/pages/organisations/organisations-info/organisation-info.component.ts
> +  organisation!: {
Why the exclamation?

2022-04-07 07:59 UTC, AjayG0910 commented on src/modules/feature-modules/admin/pages/organisations/organisations-edit/organisations-edit.component.ts
> +
I tried this logic is not working Can we have meeting and discuss this

2022-04-07 13:17 UTC, BJSS-RicardoTavares approved these changes

2022-04-07 13:23 UTC, merged