added validation fixes
nhsengland/innovation-service-transactional-frontend pull request #97
Opened 2022-01-10 11:16 UTC by AjayG0910

2022-01-10 11:30 UTC, assimoes-bjss requested changes

2022-01-10 11:30 UTC, assimoes-bjss commented on src/modules/feature-modules/innovator/pages/innovation/data-sharing/data-sharing-change.component.html
> +          <theme-form-checkbox-array arrayName="organisations" label="Please choose you data sharing preferences" [items]="organisationsList" [pageUniqueField]="false"></theme-form-checkbox-array>
there is a typo here.

2022-01-10 12:24 UTC, AjayG0910 commented on src/modules/feature-modules/innovator/pages/innovation/data-sharing/data-sharing-change.component.html
> +          <theme-form-checkbox-array arrayName="organisations" label="Please choose you data sharing preferences" [items]="organisationsList" [pageUniqueField]="false"></theme-form-checkbox-array>
Resolved

2022-01-10 14:31 UTC, assimoes-bjss approved these changes

2022-01-10 14:32 UTC, assimoes-bjss requested changes
Refer to Ricardo's review for changes in innovation-archival component.

2022-01-11 10:55 UTC, BJSS-RicardoTavares approved these changes

2022-01-11 11:02 UTC, JyotiJaiswal169 approved these changes

2022-01-11 11:51 UTC, assimoes-bjss approved these changes

2022-01-11 11:54 UTC, merged